import {Search,UserRound} from "lucide-react";
import {AppHeader} from "@/components/app-header";
import {listParticipants} from "@/features/participants/admin-data";
import {connectParticipantLine} from "@/features/participants/line-actions";
import {updateAttendance} from "@/features/participants/attendance-actions";
import {requireUser} from "@/server/authz";
const paymentLabel:Record<string,string>={PAID:"入金済",PENDING:"入金待ち",UNPAID:"未入金",CANCELLED:"キャンセル",REFUNDED:"返金済"};
const attendanceLabel:Record<string,string>={APPLIED:"申込済",PAID:"入金済",EXPECTED:"参加予定",CHECKED_IN:"受付済",ABSENT:"欠席",CANCELLED:"キャンセル",WALK_IN:"当日参加"};
export default async function ParticipantsPage({searchParams}:{searchParams:Promise<{q?:string;notice?:string}>}){const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const{q,notice}=await searchParams;const rows=await listParticipants(user,q);return <><AppHeader active="participants"/><main className="content-shell"><div className="page-heading"><div><p className="eyebrow">PARTICIPANTS</p><h1>参加者名簿</h1><p>参加者、紹介スタッフ、入金・出欠状況を横断検索できます。</p></div></div>{notice&&<div className="success-banner">{notice.startsWith("demo")?"ローカルデモでは変更を保存しません。":notice==="line-connected"?"LINEユーザーを連携しました。":"出欠状態を更新しました。"}</div>}<form className="participant-search"><Search/><input name="q" defaultValue={q} placeholder="氏名・電話番号・メール・チケット番号"/><button>検索</button></form><div className="participant-table-wrap"><table className="participant-table"><thead><tr><th>参加者</th><th>イベント</th><th>紹介者</th><th>チケット</th><th>入金</th><th>出欠・受付時刻</th><th>LINE連携</th></tr></thead><tbody>{rows.map(r=><tr key={r.registrationId}><td><strong>{r.name}</strong><small>{r.nameKana}</small><small>{r.email}</small></td><td>{r.eventName}<small>{r.appliedAt.toLocaleDateString("ja-JP")} 申込</small></td><td>{r.introducer??"—"}</td><td><code>{r.ticketNumber}</code></td><td><span className={`payment-chip payment-${r.paymentStatus.toLowerCase()}`}>{paymentLabel[r.paymentStatus]}</span></td><td>{r.attendanceStatus==="CHECKED_IN"||r.attendanceStatus==="WALK_IN"?<span>{attendanceLabel[r.attendanceStatus]}<small>{r.checkedInAt?.toLocaleString("ja-JP")}</small></span>:<form action={updateAttendance} className="attendance-form"><input type="hidden" name="registrationId" value={r.registrationId}/><select name="attendanceStatus" defaultValue={r.attendanceStatus}>{["APPLIED","PAID","EXPECTED","ABSENT","CANCELLED"].map(s=><option key={s} value={s}>{attendanceLabel[s]}</option>)}</select><button>保存</button></form>}</td><td>{r.lineConnected?<span className="line-connected">連携済</span>:<form action={connectParticipantLine} className="line-connect-form"><input type="hidden" name="participantId" value={r.id}/><input name="lineUserId" aria-label={`${r.name}のLINEユーザーID`} placeholder="Uから始まるID" required/><button>連携</button></form>}</td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-state"><UserRound/><h2>該当する参加者はいません</h2></div>}</div></main></>}
