"use server";
import {createHash,randomBytes} from "node:crypto";
import {redirect} from "next/navigation";
import {z} from "zod";
import {db} from "@/server/db";
import {isLocalDemo,requireUser} from "@/server/authz";
import {canOperateEvent} from "./authorization";
const schema=z.object({eventId:z.string().min(1),name:z.string().trim().min(1),nameKana:z.string().trim().min(1),phone:z.string().trim().min(8),email:z.string().email(),introducerStaffId:z.string().optional(),paymentStatus:z.enum(["PAID","UNPAID"])});
export async function registerWalkIn(formData:FormData){
  const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER","RECEPTION_STAFF"]);const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");const i=parsed.data;
  if(isLocalDemo())redirect(`/checkin?eventId=${i.eventId}&notice=walkin`);if(!await canOperateEvent(user,i.eventId))throw new Error("FORBIDDEN");
  await db.$transaction(async tx=>{const event=await tx.event.findUnique({where:{id:i.eventId}});if(!event)throw new Error("EVENT_NOT_FOUND");if(i.introducerStaffId&&!await tx.ticketAllocation.findFirst({where:{eventId:i.eventId,staffId:i.introducerStaffId}}))throw new Error("INVALID_INTRODUCER");const count=await tx.eventRegistration.count({where:{eventId:i.eventId,attendanceStatus:{not:"CANCELLED"}}});if(count>=event.capacity)throw new Error("EVENT_FULL");let participant=await tx.participant.findFirst({where:{OR:[{email:i.email.toLowerCase()},{phone:i.phone}]}});participant=participant??await tx.participant.create({data:{name:i.name,nameKana:i.nameKana,phone:i.phone,email:i.email.toLowerCase()}});if(await tx.eventRegistration.findUnique({where:{eventId_participantId:{eventId:i.eventId,participantId:participant.id}}}))throw new Error("PARTICIPANT_ALREADY_REGISTERED");const number=`DAY-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`;const raw=randomBytes(32).toString("base64url");const ticket=await tx.ticket.create({data:{eventId:i.eventId,participantId:participant.id,introducerStaffId:i.introducerStaffId||null,ticketNumber:number,qrTokenHash:createHash("sha256").update(raw).digest("hex"),status:"USED",paymentStatus:i.paymentStatus,issuedAt:new Date()}});await tx.eventRegistration.create({data:{eventId:i.eventId,participantId:participant.id,ticketId:ticket.id,attendanceStatus:"WALK_IN",applicationSource:"WALK_IN"}});if(i.paymentStatus==="PAID")await tx.payment.create({data:{ticketId:ticket.id,amount:event.price,paymentMethod:"ONSITE",status:"PAID",payerName:participant.name,paidAt:new Date(),confirmedBy:user.id,confirmedAt:new Date()}});const checkin=await tx.checkin.create({data:{eventId:i.eventId,ticketId:ticket.id,participantId:participant.id,checkedInBy:user.id,checkinType:"WALK_IN"}});await tx.auditLog.create({data:{actorId:user.id,action:"WALK_IN_REGISTERED",entityType:"Checkin",entityId:checkin.id,after:{ticketId:ticket.id,paymentStatus:i.paymentStatus}}})});redirect(`/checkin?eventId=${i.eventId}&notice=walkin`)
}
