import type {UserRole} from "@prisma/client";
import {db} from "@/server/db";
import {isLocalDemo} from "@/server/authz";
export type ParticipantRow={registrationId:string;id:string;name:string;nameKana:string;phone:string;email:string;eventName:string;introducer:string|null;ticketNumber:string;paymentStatus:string;attendanceStatus:string;appliedAt:Date;checkedInAt:Date|null;lineUserId:string|null;lineConnected:boolean};
const demo:ParticipantRow[]=[
  {registrationId:"r1",id:"p1",name:"山田 太郎",nameKana:"ヤマダ タロウ",phone:"090-1234-5678",email:"taro@example.com",eventName:"秋のビジネス交流会 2026",introducer:"小澤",ticketNumber:"EV-A001",paymentStatus:"PAID",attendanceStatus:"CHECKED_IN",appliedAt:new Date("2026-08-20"),checkedInAt:new Date("2026-09-12T18:01:00+09:00"),lineUserId:"Udemo01",lineConnected:true},
  {registrationId:"r2",id:"p2",name:"佐藤 花子",nameKana:"サトウ ハナコ",phone:"080-9876-5432",email:"hanako@example.com",eventName:"秋のビジネス交流会 2026",introducer:"中村",ticketNumber:"EV-A002",paymentStatus:"PENDING",attendanceStatus:"APPLIED",appliedAt:new Date("2026-08-22"),checkedInAt:null,lineUserId:null,lineConnected:false},
  {registrationId:"r3",id:"p3",name:"鈴木 健",nameKana:"スズキ ケン",phone:"070-1111-2222",email:"ken@example.com",eventName:"秋のビジネス交流会 2026",introducer:"伴",ticketNumber:"EV-A003",paymentStatus:"UNPAID",attendanceStatus:"ABSENT",appliedAt:new Date("2026-08-24"),checkedInAt:null,lineUserId:null,lineConnected:false},
];
export async function listParticipants(user:{id:string;role:UserRole},q?:string){if(isLocalDemo())return q?demo.filter(p=>[p.name,p.nameKana,p.phone,p.email,p.ticketNumber].some(v=>v.toLowerCase().includes(q.toLowerCase()))):demo;const rows=await db.eventRegistration.findMany({where:{...(user.role==="SUPER_ADMIN"?{}:{event:{OR:[{managerId:user.id},{staff:{some:{userId:user.id}}}]}}),...(q?{OR:[{participant:{name:{contains:q,mode:"insensitive"}}},{participant:{phone:{contains:q}}},{participant:{email:{contains:q,mode:"insensitive"}}},{ticket:{ticketNumber:{contains:q,mode:"insensitive"}}}]}:{})},include:{participant:true,event:true,ticket:{include:{introducer:true,checkin:true}}},orderBy:{appliedAt:"desc"}});return rows.flatMap(r=>r.ticket?[{registrationId:r.id,id:r.participant.id,name:r.participant.name,nameKana:r.participant.nameKana,phone:r.participant.phone,email:r.participant.email,eventName:r.event.name,introducer:r.ticket.introducer?.displayName??null,ticketNumber:r.ticket.ticketNumber,paymentStatus:r.ticket.paymentStatus,attendanceStatus:r.attendanceStatus,appliedAt:r.appliedAt,checkedInAt:r.ticket.checkin?.checkedInAt??null,lineUserId:r.participant.lineUserId,lineConnected:r.participant.lineConnected}]:[])}
