import type {Metadata} from "next";
import Image from "next/image";
import QRCode from "qrcode";
import {notFound} from "next/navigation";
import {CalendarDays,CheckCircle2,Clock,MapPin,ShieldCheck,TicketCheck} from "lucide-react";
import {getTicketByToken} from "@/features/tickets/data";
import {qrTokenSecret} from "@/features/tickets/token";
export const metadata:Metadata={title:"電子チケット",robots:{index:false,follow:false}};
export default async function TicketPage({params}:{params:Promise<{token:string}>}){const{token}=await params;const ticket=await getTicketByToken(token,qrTokenSecret());if(!ticket)notFound();const origin=process.env.NEXT_PUBLIC_APP_URL??"http://127.0.0.1:3000";const checkinUrl=`${origin}/checkin?token=${encodeURIComponent(token)}`;const qr=await QRCode.toDataURL(checkinUrl,{width:520,margin:2,errorCorrectionLevel:"M",color:{dark:"#0a0b0d",light:"#ffffff"}});return <main className="ticket-shell"><article className={`e-ticket${ticket.ticketBackgroundUrl?" has-bg":""}`} style={ticket.ticketBackgroundUrl?{backgroundImage:`url(${ticket.ticketBackgroundUrl})`}:undefined}><header><span>EVENT MANAGEMENT SYSTEM</span><span className="ticket-paid"><CheckCircle2/>入金済</span></header><section className="ticket-event"><p className="eyebrow">YOUR EVENT TICKET</p><h1>{ticket.eventName}</h1><div><p><CalendarDays/>{ticket.eventDate.toLocaleDateString("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"short"})}</p><p><Clock/>受付 {ticket.receptionStartTime.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})} / 開始 {ticket.startTime.toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</p><p><MapPin/>{ticket.venueName}<small>{ticket.address}</small></p></div></section><section className="ticket-owner"><span>参加者名<strong>{ticket.participantName} 様</strong></span><span>チケット番号<strong>{ticket.ticketNumber}</strong></span></section><section className="ticket-qr"><div className="ticket-qr-frame"><Image src={qr} alt="受付用QRコード" width={200} height={200} priority/></div><div className={`ticket-status ticket-${ticket.status.toLowerCase()}`}><TicketCheck/>{ticket.status==="USED"?"受付済み":"参加予定"}</div><p>当日はこのQRコードを受付スタッフへご提示ください。</p></section><footer><ShieldCheck/>QRコードに氏名・電話番号・メールアドレスは含まれていません</footer></article></main>}
