import Image from "next/image";
import QRCode from "qrcode";
import { notFound } from "next/navigation";
import { Link2,QrCode,TicketCheck,TrendingUp,Users } from "lucide-react";
import { AppHeader } from "@/components/app-header";
import { getEvent } from "@/features/events/data";
import { CopyApplyUrlButton } from "@/features/events/copy-apply-url-button";
import { saveAllocation } from "@/features/staff/actions";
import { listAllocations,listStaff } from "@/features/staff/data";
import { requireUser } from "@/server/authz";
export default async function AllocationsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{notice?:string}>}){const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const{id}=await params;const[event,allocations,staff,{notice}]=await Promise.all([getEvent(id,user),listAllocations(id),listStaff(),searchParams]);if(!event)notFound();const origin=process.env.NEXT_PUBLIC_APP_URL??"http://127.0.0.1:3000";const rows=await Promise.all(allocations.map(async a=>({...a,url:`${origin}/apply/${id}?ref=${a.referralCode}`,qr:await QRCode.toDataURL(`${origin}/apply/${id}?ref=${a.referralCode}`,{width:180,margin:1,color:{dark:"#17312f",light:"#ffffff"}})})));return <><AppHeader active="events"/><main className="content-shell"><div className="page-heading"><div><p className="eyebrow">TICKET ALLOCATION</p><h1>チケット割当</h1><p>{event.name}</p></div></div>{notice&&<div className="success-banner">{notice==="demo"?"ローカルデモでは割当を保存せず、操作フローだけ確認できます。":"割当を保存しました。"}</div>}<section className="allocation-summary"><article><TicketCheck/><span>確保合計<strong>{allocations.reduce((n,a)=>n+a.allocated,0)}枚</strong></span></article><article><Users/><span>参加者割当<strong>{allocations.reduce((n,a)=>n+a.assigned,0)}名</strong></span></article><article><TrendingUp/><span>実来場<strong>{allocations.reduce((n,a)=>n+a.checkedIn,0)}名</strong></span></article></section><form action={saveAllocation.bind(null,id)} className="allocation-form"><label>スタッフ<select name="staffId" required><option value="">選択してください</option>{staff.map(s=><option value={s.id} key={s.id}>{s.displayName}</option>)}</select></label><label>確保枚数<input name="quantity" type="number" min="0" max={event.capacity} required/></label><button>割当を保存</button></form><section className="allocation-grid">{rows.map(a=>{const use=a.allocated?Math.round(a.assigned/a.allocated*100):0;const payment=a.assigned?Math.round(a.paid/a.assigned*100):0;const visit=a.paid?Math.round(a.checkedIn/a.paid*100):0;return <article className="allocation-card" key={a.id}><header><div className="avatar">{a.staffName.slice(0,1)}</div><div><h2>{a.staffName}</h2><span>残り {a.allocated-a.assigned}枚</span></div><strong>{a.allocated}<small>枚確保</small></strong></header><div className="allocation-numbers"><span>割当<strong>{a.assigned}</strong></span><span>入金<strong>{a.paid}</strong></span><span>来場<strong>{a.checkedIn}</strong></span></div><div className="rate-list"><span>消化率 <strong>{use}%</strong></span><span>入金率 <strong>{payment}%</strong></span><span>来場率 <strong>{visit}%</strong></span></div><div className="referral-box"><Image src={a.qr} alt={`${a.staffName}専用申込QR`} width={112} height={112}/><div><span><QrCode/>専用申込QR</span><code>{a.url}</code><CopyApplyUrlButton text={a.url}/><a href={a.url} target="_blank" rel="noreferrer"><Link2/>申込画面を開く</a></div></div></article>})}</section></main></>}
