import type {NotificationType,Prisma} from "@prisma/client";
import {db} from "@/server/db";
import {issueTicketToken,qrTokenSecret} from "@/features/tickets/token";
import {notificationMessage} from "./domain";
import {notificationRules} from "./schedule";
import {pushLineMessage} from "./line";
export async function queueParticipantNotification(tx:Prisma.TransactionClient,eventId:string,participantId:string,type:NotificationType,scheduledAt=new Date()){await tx.notificationJob.create({data:{eventId,type,scheduledAt,payload:{participantId}}})}
export async function createReminderJobs(now=new Date()){const events=await db.event.findMany({where:{lineNotifications:true,status:"PUBLISHED",startTime:{gt:now}},include:{registrations:{where:{attendanceStatus:{not:"CANCELLED"}},select:{participantId:true}}}});let created=0;for(const event of events){const rules=notificationRules(event,event);for(const rule of rules){if(!rule.enabled||rule.scheduledAt<=now)continue;for(const registration of event.registrations){const existing=await db.notificationJob.findFirst({where:{eventId:event.id,type:rule.type,status:"PENDING",payload:{equals:{participantId:registration.participantId}}}});if(existing){if(existing.scheduledAt.getTime()!==rule.scheduledAt.getTime())await db.notificationJob.update({where:{id:existing.id},data:{scheduledAt:rule.scheduledAt}})}else{await db.notificationJob.create({data:{eventId:event.id,type:rule.type,scheduledAt:rule.scheduledAt,payload:{participantId:registration.participantId}}});created++}}}}return created}
export async function processDueNotificationJobs(limit=50){const jobs=await db.notificationJob.findMany({where:{status:"PENDING",scheduledAt:{lte:new Date()}},orderBy:{scheduledAt:"asc"},take:limit});let sent=0,failed=0;for(const job of jobs){const claimed=await db.notificationJob.updateMany({where:{id:job.id,status:"PENDING"},data:{status:"PROCESSING",attempts:{increment:1}}});if(!claimed.count)continue;const participantId=typeof job.payload==="object"&&job.payload&&!Array.isArray(job.payload)&&"participantId" in job.payload?String(job.payload.participantId):"";const data=await db.eventRegistration.findUnique({where:{eventId_participantId:{eventId:job.eventId,participantId}},include:{participant:true,event:true,ticket:true}});if(!data){await db.notificationJob.update({where:{id:job.id},data:{status:"FAILED"}});failed++;continue}const ticketUrl=data.ticket?`${process.env.NEXT_PUBLIC_APP_URL}/ticket/${issueTicketToken(data.ticket.id,data.ticket.qrTokenVersion,qrTokenSecret())}`:undefined;const message=notificationMessage(job.type,{name:data.participant.name,eventName:data.event.name,startTime:data.event.startTime,receptionStartTime:data.event.receptionStartTime,venueName:data.event.venueName,bankInformation:data.event.bankInformation,ticketUrl,beforeStartMinutes:data.event.beforeStartNotificationMinutes});try{if(!data.participant.lineConnected||!data.participant.lineUserId)throw new Error("PARTICIPANT_NOT_CONNECTED_TO_LINE");await pushLineMessage(data.participant.lineUserId,message);await db.$transaction([db.notificationLog.create({data:{participantId,eventId:job.eventId,type:job.type,message,status:"SENT",sentAt:new Date()}}),db.notificationJob.update({where:{id:job.id},data:{status:"SENT"}})]);sent++}catch(error){const errorMessage=error instanceof Error?error.message:"UNKNOWN_ERROR";await db.$transaction([db.notificationLog.create({data:{participantId,eventId:job.eventId,type:job.type,message,status:"FAILED",errorMessage}}),db.notificationJob.update({where:{id:job.id},data:{status:job.attempts+1>=3?"FAILED":"PENDING",scheduledAt:new Date(Date.now()+15*60*1000)}})]);failed++}}return {processed:sent+failed,sent,failed}}
