"use server";
import { randomBytes,createHash } from "node:crypto";
import { hash } from "bcryptjs";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/server/db";
import { isLocalDemo,requireUser } from "@/server/authz";
export async function createStaff(formData:FormData){const actor=await requireUser(["SUPER_ADMIN"]);const parsed=z.object({name:z.string().trim().min(1).max(80),email:z.string().email(),password:z.string().min(12).max(128)}).safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");if(isLocalDemo())redirect("/staff?notice=demo");await db.$transaction(async tx=>{const user=await tx.user.create({data:{name:parsed.data.name,email:parsed.data.email.toLowerCase(),passwordHash:await hash(parsed.data.password,12),role:"EVENT_MANAGER",staffProfile:{create:{displayName:parsed.data.name}}}});await tx.auditLog.create({data:{actorId:actor.id,action:"STAFF_CREATED",entityType:"User",entityId:user.id,after:{name:user.name,email:user.email,role:user.role}}})});revalidatePath("/staff");redirect("/staff?notice=created")}
export async function saveAllocation(eventId:string,formData:FormData){const actor=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const parsed=z.object({staffId:z.string().min(1),quantity:z.coerce.number().int().min(0).max(10000)}).safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");if(isLocalDemo())redirect(`/events/${eventId}/allocations?notice=demo`);const existing=await db.ticketAllocation.findUnique({where:{eventId_staffId:{eventId,staffId:parsed.data.staffId}}});if(existing&&parsed.data.quantity<existing.assignedQuantity)throw new Error("ALLOCATED_BELOW_ASSIGNED");const code=randomBytes(18).toString("base64url");await db.$transaction(async tx=>{const allocation=await tx.ticketAllocation.upsert({where:{eventId_staffId:{eventId,staffId:parsed.data.staffId}},update:{allocatedQuantity:parsed.data.quantity},create:{eventId,staffId:parsed.data.staffId,allocatedQuantity:parsed.data.quantity,referralCode:code,referralTokenHash:createHash("sha256").update(code).digest("hex")}});await tx.auditLog.create({data:{actorId:actor.id,action:"TICKET_ALLOCATION_SAVED",entityType:"TicketAllocation",entityId:allocation.id,before:existing??undefined,after:allocation}})});revalidatePath(`/events/${eventId}/allocations`);redirect(`/events/${eventId}/allocations?notice=saved`)}
