"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {db} from "@/server/db";
import {isLocalDemo,requireUser} from "@/server/authz";
import {hashTicketToken,issueTicketToken,qrTokenSecret} from "@/features/tickets/token";
import {queueParticipantNotification} from "@/features/notifications/service";
import {assertPaymentTransition} from "./domain";
const schema=z.object({status:z.enum(["UNPAID","PENDING","PAID","CANCELLED","REFUNDED"]),payerName:z.string().trim().max(120).optional(),paidAt:z.string().optional(),amount:z.coerce.number().int().min(0).optional()});
export async function updatePayment(ticketId:string,formData:FormData){const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");if(isLocalDemo())redirect("/payments?notice=demo");const ticket=await db.ticket.findUnique({where:{id:ticketId},include:{event:true}});if(!ticket)throw new Error("TICKET_NOT_FOUND");if(user.role!=="SUPER_ADMIN"&&ticket.event.managerId!==user.id)throw new Error("FORBIDDEN");assertPaymentTransition(ticket.paymentStatus,parsed.data.status);const amount=user.role==="SUPER_ADMIN"&&parsed.data.amount!==undefined?parsed.data.amount:ticket.event.price;const activating=parsed.data.status==="PAID";const token=activating?issueTicketToken(ticket.id,ticket.qrTokenVersion,qrTokenSecret()):null;await db.$transaction(async tx=>{const payment=await tx.payment.create({data:{ticketId,amount,paymentMethod:"BANK_TRANSFER",status:parsed.data.status,payerName:parsed.data.payerName||null,paidAt:parsed.data.paidAt?new Date(parsed.data.paidAt):activating?new Date():null,confirmedBy:user.id,confirmedAt:new Date()}});await tx.ticket.update({where:{id:ticketId},data:{paymentStatus:parsed.data.status,status:activating?"ACTIVE":parsed.data.status==="CANCELLED"||parsed.data.status==="REFUNDED"?"CANCELLED":ticket.status,...(token?{qrTokenHash:hashTicketToken(token),issuedAt:new Date()}:{})}});await tx.eventRegistration.updateMany({where:{ticketId},data:{attendanceStatus:activating?"PAID":parsed.data.status==="CANCELLED"||parsed.data.status==="REFUNDED"?"CANCELLED":"APPLIED"}});if(activating&&ticket.event.lineNotifications){await tx.notificationJob.updateMany({where:{eventId:ticket.eventId,type:"PAYMENT_REMINDER",status:"PENDING",payload:{equals:{participantId:ticket.participantId}}},data:{status:"CANCELLED"}});await queueParticipantNotification(tx,ticket.eventId,ticket.participantId,"PAYMENT_CONFIRMED");await queueParticipantNotification(tx,ticket.eventId,ticket.participantId,"TICKET")}await tx.auditLog.create({data:{actorId:user.id,action:"PAYMENT_STATUS_UPDATED",entityType:"Payment",entityId:payment.id,before:{status:ticket.paymentStatus},after:{status:parsed.data.status,amount,ticketActivated:activating}}})});revalidatePath("/payments");redirect("/payments?notice=saved")}
export async function updateOrderPayment(orderId:string,formData:FormData){const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");if(isLocalDemo())redirect("/payments?notice=demo");const order=await db.ticketOrder.findUnique({where:{id:orderId},include:{event:true,tickets:true}});if(!order)throw new Error("ORDER_NOT_FOUND");if(user.role!=="SUPER_ADMIN"&&order.event.managerId!==user.id)throw new Error("FORBIDDEN");for(const ticket of order.tickets)assertPaymentTransition(ticket.paymentStatus,parsed.data.status);const amount=user.role==="SUPER_ADMIN"&&parsed.data.amount!==undefined?parsed.data.amount:order.event.price;const activating=parsed.data.status==="PAID";await db.$transaction(async tx=>{for(const ticket of order.tickets){const token=activating?issueTicketToken(ticket.id,ticket.qrTokenVersion,qrTokenSecret()):null;const payment=await tx.payment.create({data:{ticketId:ticket.id,amount,paymentMethod:"BANK_TRANSFER",status:parsed.data.status,payerName:parsed.data.payerName||null,paidAt:parsed.data.paidAt?new Date(parsed.data.paidAt):activating?new Date():null,confirmedBy:user.id,confirmedAt:new Date()}});await tx.ticket.update({where:{id:ticket.id},data:{paymentStatus:parsed.data.status,status:activating?"ACTIVE":parsed.data.status==="CANCELLED"||parsed.data.status==="REFUNDED"?"CANCELLED":ticket.status,...(token?{qrTokenHash:hashTicketToken(token),issuedAt:new Date()}:{})}});await tx.eventRegistration.updateMany({where:{ticketId:ticket.id},data:{attendanceStatus:activating?"PAID":parsed.data.status==="CANCELLED"||parsed.data.status==="REFUNDED"?"CANCELLED":"APPLIED"}});if(activating&&order.event.lineNotifications&&ticket.claimed){await tx.notificationJob.updateMany({where:{eventId:ticket.eventId,type:"PAYMENT_REMINDER",status:"PENDING",payload:{equals:{participantId:ticket.participantId}}},data:{status:"CANCELLED"}});await queueParticipantNotification(tx,ticket.eventId,ticket.participantId,"PAYMENT_CONFIRMED");await queueParticipantNotification(tx,ticket.eventId,ticket.participantId,"TICKET")}await tx.auditLog.create({data:{actorId:user.id,action:"PAYMENT_STATUS_UPDATED",entityType:"Payment",entityId:payment.id,before:{status:ticket.paymentStatus},after:{status:parsed.data.status,amount,ticketActivated:activating,orderId}}})}});revalidatePath("/payments");redirect("/payments?notice=saved")}
