"use server";
import {revalidatePath} from "next/cache";
import {redirect} from "next/navigation";
import {z} from "zod";
import {db} from "@/server/db";
import {isLocalDemo,requireUser} from "@/server/authz";
import {hashTicketToken,issueTicketToken,qrTokenSecret} from "@/features/tickets/token";
import {canTransferTicket,nextQrVersion} from "./domain";
import {generateLineLinkCode} from "@/features/participants/line-link-code";
const schema=z.object({ticketId:z.string().min(1),name:z.string().trim().min(1).max(100),nameKana:z.string().trim().min(1).max(120),phone:z.string().trim().min(8).max(20),email:z.string().email(),reason:z.string().trim().min(5).max(500)});
export async function transferTicket(formData:FormData){const user=await requireUser(["SUPER_ADMIN","EVENT_MANAGER"]);const parsed=schema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("INVALID_INPUT");if(isLocalDemo())redirect("/transfers?notice=demo");const i=parsed.data;const ticket=await db.ticket.findUnique({where:{id:i.ticketId},include:{event:true,checkin:true}});if(!ticket)throw new Error("TICKET_NOT_FOUND");if(user.role!=="SUPER_ADMIN"&&ticket.event.managerId!==user.id)throw new Error("FORBIDDEN");if(!canTransferTicket({status:ticket.status,hasCheckin:Boolean(ticket.checkin)}))throw new Error("TICKET_NOT_TRANSFERABLE");const version=nextQrVersion(ticket.qrTokenVersion);const newToken=issueTicketToken(ticket.id,version,qrTokenSecret());await db.$transaction(async tx=>{let participant=await tx.participant.findFirst({where:{OR:[{email:i.email.toLowerCase()},{phone:i.phone}]}});participant=participant??await tx.participant.create({data:{name:i.name,nameKana:i.nameKana,phone:i.phone,email:i.email.toLowerCase(),lineLinkCode:generateLineLinkCode()}});const duplicate=await tx.eventRegistration.findUnique({where:{eventId_participantId:{eventId:ticket.eventId,participantId:participant.id}}});if(duplicate)throw new Error("NEW_PARTICIPANT_ALREADY_REGISTERED");const transfer=await tx.ticketTransfer.create({data:{ticketId:ticket.id,oldParticipantId:ticket.participantId,newParticipantId:participant.id,transferredBy:user.id,reason:i.reason,oldQrTokenHash:ticket.qrTokenHash}});await tx.ticket.update({where:{id:ticket.id},data:{participantId:participant.id,qrTokenVersion:version,qrTokenHash:hashTicketToken(newToken),transferredAt:new Date()}});await tx.eventRegistration.update({where:{ticketId:ticket.id},data:{participantId:participant.id}});await tx.auditLog.create({data:{actorId:user.id,action:"TICKET_TRANSFERRED",entityType:"TicketTransfer",entityId:transfer.id,before:{participantId:ticket.participantId,qrTokenVersion:ticket.qrTokenVersion},after:{participantId:participant.id,qrTokenVersion:version,paymentStatus:ticket.paymentStatus}}})});revalidatePath("/transfers");redirect("/transfers?notice=success")}
